version: '3'

services:
  api:
    image: go-api-dev
    container_name: go-api-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - mongo-db
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
    networks:
      - app

  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: always
    networks:
      - app

networks:
  app:
