name: Api Tests

on:
  pull_request:
    branches: [ main ]

jobs:

  tests-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Test Environment Docker
      run: docker-compose -f ./api/docker-compose.test.yml build
    - name: Run Tests
      run: docker-compose -f ./api/docker-compose.test.yml run api
